#pragma once

enum class eHandlingType
{
    HANDLING_TYPE_BIKE,
    HANDLING_TYPE_FLYING,
    HANDLING_TYPE_VERTICAL_FLYING,
    HANDLING_TYPE_BOAT,
    HANDLING_TYPE_SEAPLANE,
    HANDLING_TYPE_SUBMARINE,
    HANDLING_TYPE_TRAIN,
    HANDLING_TYPE_TRAILER,
    HANDLING_TYPE_CAR,
    HANDLING_TYPE_WEAPON,
    HANDLING_TYPE_MAX_TYPES
};